# Source: https://github.com/marketplace/actions/vale-linter?version=v2.0.1

name: reviewdog
on: pull_request

jobs:
  changed_files:
    runs-on: ubuntu-latest    
    steps: 
      - uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        run: echo "FILES=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
      - name: Print changed files
        run: echo ${{ steps.changes.output.FILES}}
  vale:
    name: Run vale
    runs-on: ubuntu-latest
    needs: changed_files
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@reviewdog
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: needs.changed_files.output.all