name: Sync
on: workflow_dispatch
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Syncing main to development
    steps:       
      - name: Get date and time
        id: date
        run: echo "NOW=$(date +'%Y%m%d-%k%M')"
      - name: Checkout repository
        uses: actions/checkout@v3
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`
      - name: Create a branch
        run: git switch -c sync-development-${{steps.date.outputs.NOW}} origin/main
      - name: Create a PR to development
        run: gh pr create --base origin/development --title "Sync main to development"