name: Sync
on: workflow_dispatch
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Syncing main to development
    steps:       
      - name: Checkout development branch
        uses: actions/checkout@v3        
      - name: Create a PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add report file
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: true
          branch: sync-to-development
          base: development
          delete-branch: true
          title: Sync main to development