name: Sync
on: workflow_dispatch
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Syncing main to development
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Open pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "main"
          destination_branch: "development"
          pr_title: "Synching main to development"