name: Sync
on: workflow_dispatch
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Syncing main to development
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Open pull request
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "main"
          TO_BRANCH: "development"