name: Sync
on: workflow_dispatch
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Syncing main to development
    steps:       
      - name: Get date and time
        id: date        
        run: echo "NOW=$(date +'%Y%m%d-%k%M')"
      - name: Checkout main branch
        uses: actions/checkout@v3
        with: 
          ref: main
      - name: Create a branch
        run: git switch -c sync-to-development
      - name: Create a PR to development
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: sync-to-development
          target_branch: development
          title: Sync development into main