name: Sync
on: workflow_dispatch
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Syncing main to development
    steps:       
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`
      - name: Get date and time
        id: date
        run: echo "NOW=$(date +'%Y%m%d-%k%M')"
      - name: Checkout main branch
        uses: actions/checkout@v3
        with: 
          ref: main
      - name: Create a branch
        run: git switch -c sync-to-development
      - name: Create a PR to development
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: sync-to-development
          base: development
          title: Sync development into main